</$objtype/mkfile

LIB=../libsha3.a
OFILES=\
	main.$O\

HFILES=\
	sha3_224.c\
	sha3_256.c\
	sha3_384.c\
	sha3_512.c\
	keccak_224.c\
	keccak_256.c\
	keccak_384.c\
	keccak_512.c\
	keccak_256full.c\
	shake_128.c\
	shake_256.c\
	turboshake_128.c\
	turboshake_256.c\

</sys/src/cmd/mkone

test:VQ: $O.out
	6.out
